export const  SPANISH={
    title:'Ver el clima usando React',
    formLegend:'Descubre el clima en cualquier ciudad',
    cityPlaceholder:'Nombre de la ciudad',
    buttonText:'Buscar',
    otherLanguage:'English version',
    cityNotFound:'No se encontró la ciudad',
    intro:'El clima en ',
    temperatureLabel:'Temperatura:',
    pressureLabel:'Presión:',
    humidityLabel:'Humedad:',
    windLabel:'Viento:',
    weatherConditions:{
       "01d":"Cielo despejado",
       "01n":"CIelo despejado",
       "02d":"Pocas nubes",
       "02n":"Pocas nubes",
       "03d":"Nubes dispersas",
       "03n":"Nubes dispersas",
       "04d":"Nubes abundantes",
       "04n":"Nubes abundantes",
       "09d":"Lluvia intensa",
       "09n":"Lluvia intensa",
       "10d":"Lluvia",
       "10n":"Lluvia",
       "11d":"Tormenta eléctrica",
       "11n":"Tormenta eléctrica",
       "13d":"Nieve",
       "13n":"Nieve",
       "50d":"Neblina o ventoso",
       "50n":"Neblina o ventoso",
    },
    author:'Hecho por Sergio',
    github:'Click para ver en GitHub'
}
export const  ENGLISH={
    title:'See the weather using React',
    formLegend:'Discover the weather in any city',
    cityPlaceholder:'Write the city name',
    buttonText:'Search',
    otherLanguage:'Versión en español',
    cityNotFound:'The city could not be found',
    intro:'The weather in ',
    temperatureLabel:'Temperature:',
    pressureLabel:'Pressure:',
    humidityLabel:'Humidity:',
    windLabel:'Wind:',
    weatherConditions:{
        "01d":"Clear sky",
        "01n":"Clear sky",
        "02d":"Few clouds",
        "02n":"Few clouds",
        "03d":"Scattered clouds",
        "03n":"Scattered clouds",
        "04d":"Broken clouds",
        "04n":"Broken clouds",
        "09d":"Shower rain",
        "09n":"Shower rain",
        "10d":"Rainy",
        "10n":"Rainy",
        "11d":"Thunderstorm",
        "11n":"Thunderstorm",
        "13d":"Snowy",
        "13n":"Snowy",
        "50d":"Misty or windy",
        "50n":"Misty or windy",
     },
     author:'Made by Sergio',
     github:'Click to see on Github'
}